"""add_notification_settings

Revision ID: 85a5d8f45efa
Revises: f80ecb1b1c74
Create Date: 2026-03-28 04:23:30.495692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a5d8f45efa'
down_revision: Union[str, None] = 'f80ecb1b1c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email_low_stock', sa.Boolean(), nullable=False),
    sa.Column('email_new_order', sa.Boolean(), nullable=False),
    sa.Column('email_payment', sa.Boolean(), nullable=False),
    sa.Column('low_stock_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.drop_index('ix_inventory_tenant_id', table_name='inventory')
    op.drop_index('ix_inventory_variant_id', table_name='inventory')
    op.drop_index('ix_inventory_warehouse_id', table_name='inventory')
    op.drop_index('ix_orders_channel_id', table_name='orders')
    op.drop_index('ix_product_variants_product_id', table_name='product_variants')
    op.drop_index('ix_product_variants_tenant_id', table_name='product_variants')
    op.drop_index('ix_products_tenant_id', table_name='products')
    op.drop_index('ix_stock_movements_created_at', table_name='stock_movements')
    op.drop_index('ix_stock_movements_inventory_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_tenant_id', table_name='stock_movements')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_index('ix_warehouses_tenant_id', table_name='warehouses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_warehouses_tenant_id', 'warehouses', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_stock_movements_tenant_id', 'stock_movements', ['tenant_id'], unique=False)
    op.create_index('ix_stock_movements_inventory_id', 'stock_movements', ['inventory_id'], unique=False)
    op.create_index('ix_stock_movements_created_at', 'stock_movements', ['created_at'], unique=False)
    op.create_index('ix_products_tenant_id', 'products', ['tenant_id'], unique=False)
    op.create_index('ix_product_variants_tenant_id', 'product_variants', ['tenant_id'], unique=False)
    op.create_index('ix_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_index('ix_orders_channel_id', 'orders', ['channel_id'], unique=False)
    op.create_index('ix_inventory_warehouse_id', 'inventory', ['warehouse_id'], unique=False)
    op.create_index('ix_inventory_variant_id', 'inventory', ['variant_id'], unique=False)
    op.create_index('ix_inventory_tenant_id', 'inventory', ['tenant_id'], unique=False)
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
