"""add_user_permissions

Revision ID: d2607bd2042b
Revises: a5df782c679e
Create Date: 2026-03-28 15:45:50.522483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2607bd2042b'
down_revision: Union[str, None] = 'a5df782c679e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first
    op.add_column('users', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # 2. Update existing rows with default []
    op.execute("UPDATE users SET permissions = '[]'")
    
    # 3. Alter column to be NOT NULL
    op.alter_column('users', 'permissions', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
