"""add_tenant_settings_and_ai_keys

Revision ID: f80ecb1b1c74
Revises: h7f2g5h8e967
Create Date: 2026-03-28 04:09:09.703903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80ecb1b1c74'
down_revision: Union[str, None] = 'h7f2g5h8e967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_keys',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'GEMINI', 'AZURE_OPENAI', 'MISTRAL', name='ai_provider'), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('key_preview', sa.String(length=20), nullable=False),
    sa.Column('model_override', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='uq_ai_provider_keys_tenant_provider')
    )
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('weight_unit', sa.Enum('KG', 'G', 'LB', 'OZ', name='weight_unit'), nullable=False),
    sa.Column('dimension_unit', sa.Enum('CM', 'M', 'IN', 'FT', name='dimension_unit'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('date_format', sa.Enum('DMY', 'MDY', 'YMD', name='date_format'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_settings')
    op.drop_table('ai_provider_keys')
    # ### end Alembic commands ###
